#pessoa = input("digite o nome da pessoa")
#print ("boa noite",pessoa)
#idade = input("qual a sua idade? ")
#print("nossa! voce só tem ", idade," anos ")
#email = input("digite seu email")
#print("seu email é",email)
numero = input("digite seu numero")
outronumero = input("digite outro numero")
print("a soma é ", float(numero) + float(outronumero))
